@startuml

left to right direction

actor 管理者
actor ユーザー

rectangle ショッピングサイトシステム{
	管理者 --> (ログイン・ログアウト)
	管理者 --> (商品のラインナップを編集する)
	管理者 --> (商品情報を編集する)
	管理者 --> (商品情報を見る)
	管理者 --> (商品のラインナップを見る)
	管理者 --> (注文の確認をする)

	(ログイン・ログアウト) <--  ユーザー
	(商品のラインナップを見る) <--  ユーザー
	(商品情報を見る) <--  ユーザー
	(商品を注文する) <--  ユーザー
	(注文の確認をする) <--  ユーザー
	(商品の注文をキャンセルする) <--  ユーザー
	(支払い情報を編集する) <--  ユーザー
}
	管理者 --> (サーバ起動)


@enduml